server:
  port: 9001

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/11439311-814c-45af-91da-11a6029b5332/discovery/v2.0/keys
      client:
        registration:
          client-c:
            provider: azure
            client-id: de838587-c53a-4f81-a57e-c530d01edab0
            client-secret: MmpcLkI:9f-Qm.Vkwz4sJHa:y3XLQom0
            authorization-grant-type: client_credentials
            scope: api://microservice-c/.default
          client-c-exchange:
            provider: azure
            client-id: client-c
            client-secret: secret
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: authority-c
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/11439311-814c-45af-91da-11a6029b5332/v2.0

oauth2:
  resource:
    services:
      service-c:
        uri: http://localhost:9002/service-c
